server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.0:3306/dbname?characterEncoding=utf8&useSSL=false
    username: root
    password: root

#自定义配置项
string.value: bite666
string:
  value2: ""
  str1: Hello \n Spring Boot.
  str2: 'Hello \n Spring Boot.'
  str3: "Hello \n Spring Boot."

student:
  id: 1
  name: Java
  age: 18
dbtypes:
  name:
    - mysql
    - sqlserver
    - db2
  map:
    k1: kk1
    k2: kk2
    k3: kk3

#日志配置
logging:
  level:
    root: info
    com:
      bite:
        demo:
          ioc:
            controller: debug
  file:
    path: logger/    #配置日志路径
    name: logger1/ioc.log     #配置日志名称
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i
#      max-file-size: 2KB
  pattern:
    console: '%d{MM-dd HH:mm:ss.SSS} %c %M %L [%thread] %m%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %c %M %L [%thread] %m%n'